stages:
    - build
    - package
    - testing
    - deploy

variables:
    APP_VERISON: $CI_PIPELINE_IID

build docker image:
    rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - changes:
      - app/app.py

    stage: package
    image: docker:20.10.12
    services:
      - docker:20.10.12-dind
    before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    script:
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $CI_REGISTRY_USER/$IMAGE_NAME:latest
    - docker image ls
    - docker push $CI_REGISTRY_USER/$IMAGE_NAME:latest

